### ISSUE TITLE
Provide Android Studio plugin via Plugin-Repository

### ISSUE THREAD

**Issue by ajans** [sockeqwe/ParcelablePlease#18]
This would tremendously ease the update-process of your awesome plugin as we developers get a update-notification and its simply a two-click process to update your plugin this way.

Here is the official documentation for that:

https://www.jetbrains.com/idea/help/preparing-plugins-for-publishing.html

**Comment by sockeqwe** [comment]
I think it requires a paid jetbrains account to be able to publish the Plugin via Plugin repository.

**Comment by ajans** [comment]
I just registered there and had a look, it seems to me you can simply register and upload a plugin to the global Intellij Plugin database:

![intellij-new-plugin](https://cloud.githubusercontent.com/assets/3482744/11784828/b90e8384-a27e-11e5-8382-415d5ebd9735.png)

If you open the Repository browser in Android Studio and search for "Parcel", you can see some Open-Source plugins there from indie developers, which indicates to me you could do this.

Please select the category "Code Tools" as it is the most appropriate for your plugin.

**Comment by ajans** [comment]
Alternatively, you could also host your own plugin-repository and tell people in the Installation guide how to add it to Android Studio (via the "Manage repositories" button).

Example for the JRebel-Android plugin repository:

URL:

    https://dl.zeroturnaround.com/jrebel-android/ide-studio/updatePlugins.xml

updatePlugins.xml:

    <plugins>
      <plugin id="JRebelAndroidPlugin" url="http://dl.zeroturnaround.com/jrebel-android/ide-studio/jrebel-for-android.zip" version="0.9.46" />
    </plugins>

**Comment by sockeqwe** [comment]
I will try to submit on official repo this evening. Last time i cheched that (almost 2 years ago) I stucked because of paying for an account. thanks for taking time to check that

**Comment by sockeqwe** [comment]
Done, 
plugin is waiting for approve ... Hope to be available soon

https://plugins.jetbrains.com/plugin/8099?pr=

**Comment by ajans** [comment]
Awesome, thank you!
