### ISSUE TITLE
Can't find ParcelablePlease Plugin

### ISSUE THREAD

**Issue by bytehala** [sockeqwe/ParcelablePlease#21]
I just downloaded from [jetbrains](https://plugins.jetbrains.com/plugin/8099?pr=) and installed from disk, because:

![](http://i.imgur.com/IjQ1J7g.png)

**Comment by sockeqwe** [comment]
I will check that, in the mean time you can download it from here: https://github.com/sockeqwe/ParcelablePlease/blob/master/ParcelablePlease-intellij-plugin/ParcelablePlease-intellij-plugin.jar?raw=true

Then in android Studios plugin dialog choose "install from disk" and then choose the downloaded jar file

**Comment by sockeqwe** [comment]
Is fixed now
