### ISSUE TITLE
Baggers.class multi dex issue

### ISSUE THREAD

**Issue by lzyzsd** [sockeqwe/ParcelablePlease#6]
when use in diff modules, multi dex issue occurs, caused by multi Baggers.class

**Comment by sockeqwe** [comment]
I see, I will fix that soon.

**Comment by sockeqwe** [comment]
@lzyzsd  this issue is fixed with the version 1.0.1 which I have deployed a few seconds ago. It take some hours until this version is synced in maven central. Please let me know if you still get problems.
