### ISSUE TITLE
another anotation plug-in

### ISSUE THREAD

**Issue by frakc** [sockeqwe/ParcelablePlease#7]
Hello.
Is there another option for Hugo Visser's plug-in, as it interfere with facebook sdk and makes it crash at compile time?

**Comment by sockeqwe** [comment]
Im afraid, never heard of such an issue with apt-plugin. It could work (untested) with `compile`.

```groovy
compile com.hannesdorfmann.parcelableplease:processor:x.x.x'
```
In that case the compiler will be packed in your apk, but It just few classes which should be acceptable though.

 I think `provided` does not work, but you could try it:
```groovy
provided com.hannesdorfmann.parcelableplease:processor:x.x.x'
```
